# Generated by Django 3.2.23 on 2023-11-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
