# Usa una imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el código de la aplicación al contenedor
COPY . /app

# Instala las dependencias de la aplicación
RUN pip install Flask

RUN pip install requests

# Expone el puerto 5000 para la aplicación Flask
EXPOSE 5000

# Configura y ejecuta el servidor de Flask
CMD ["python", "server/server.py"]
